---
# GitHub Actions workflow for commits pushed to the repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - run: ./gradlew javadoc build --console=plain --no-daemon --stacktrace

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - run: ./gradlew javadoc build --console=plain --no-daemon --stacktrace
        shell: bash
