---
# GitHub Actions workflow for commits pushed to the repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x gradlew
      - run: ./gradlew javadoc build --console=plain --no-daemon --stacktrace

  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew javadoc build --console=plain --no-daemon --stacktrace

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - run: ./gradlew javadoc build --console=plain --no-daemon --stacktrace
        shell: bash
